version: "2"

volumes:
  postgres_data: {}

services:
  web:
    build: .
    env_file: local.env
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
     - ./src:/usr/src/app

  db:
    image: postgres
    env_file: local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
