apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: my-secret-pw
        image: postgres
        name: db
        ports:
        - containerPort: 5432
        resources: {}
status: {}
